version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - aws_access_key_id=${aws_access_key_id}
      - aws_secret_access_key=${aws_secret_access_key}
      - aws_session_token=${aws_session_token}
    volumes:
      - ~/.aws/:/root/.aws:ro
